### ISSUE TITLE
Oculus DK2

### ISSUE THREAD

**Issue by renambot-uic** [rlk/panoptic#2]
On Windows (7, I think) it runs fullscreen on the monitor and tracks fine, but I don't get the video signal to the device. Other demos (Unity3D, binaries, ...) seem to work fine.
Any hint ?

**Comment by rlk** [comment]
Hi Luc!

Are you using Direct Mode? It appears that OpenGL apps must use Extended
Mode. I can't state with 100% certainty, but it seems like only D3D apps
can use Direct Mode.

**Comment by renambot-uic** [comment]
You're right, it works fine in extended mode.
Sorry for the trouble.
